# Generated by Django 4.2.8 on 2023-12-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project1',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
