# Generated by Django 4.2.8 on 2023-12-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_project1_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='project1',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment/'),
        ),
    ]
