# Generated by Django 4.2.8 on 2023-12-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_project1_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensee',
            name='expense_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
