# Generated by Django 4.2.8 on 2023-12-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_expensee_expense_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project1',
            name='project_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
