# Generated by Django 4.2.8 on 2023-12-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_project1_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_table',
            name='first_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
