# Generated by Django 4.2.8 on 2023-12-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_alter_vendor_table_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensee',
            name='expense_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
