# Generated by Django 4.2.8 on 2023-12-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_alter_expensee_expense_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='proj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.project1'),
        ),
    ]
