# Generated by Django 4.2.8 on 2023-12-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_payroll_proj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='Phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='alias',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='blood',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='joindate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='parent',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='spouse_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
