# Generated by Django 4.2.8 on 2023-12-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_alter_payroll_phone_alter_payroll_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensee',
            name='tax2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
