# Generated by Django 4.2.8 on 2023-12-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_expensee_tax2_alter_payroll_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='projcode',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
