# Generated by Django 4.2.8 on 2023-12-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0011_payroll_projcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernamez',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.payroll'),
        ),
    ]
